server:
  port: 8084


spring.datasource.url: jdbc:mysql://192.168.161.114:3306/gts01?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username: gts
spring.datasource.password: mysql
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.validationQuery: SELECT 1
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat


#redis数据库默认使用db0
spring.redis.database: 2
spring.redis.password:
spring.redis.port: 6379
spring.redis.host: 127.0.0.1
# 连接超时时间
spring.redis.timeout: 5000
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.lettuce.pool.max-active: 3
# 连接池中的最小空闲连接
spring.redis.lettuce.pool.min-idle: 2
# 连接池中的最大空闲连接
spring.redis.lettuce.pool.max-idle: 3
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.lettuce.pool.max-wait: -1
#在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
spring.redis.lettuce.shutdown-timeout: 100
#是否缓存空值
spring.cache.redis.cache-null-values: false


logging.level.org.springframework: debug
logging.level.com.dhb.mybatis.cache.orm.mapper: debug