server:
  port: 8089
  
spring:
  application:
    name: bank-transfer-bank2

dubbo:
  scan:
    base-packages: com.dhb.bank.transfer.bank2
  protocol:
    name: dubbo
    port: 12346
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost


#数据源配置 默认Hikari
spring.datasource.url: jdbc:mysql://192.168.161.114:3306/gts02?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username: gts
spring.datasource.password: mysql
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  root: info
  org.springframework: debug
  org.apache.ibatis: info
  org.dromara.hmily.bonuspoint: debug
  org.dromara.hmily.lottery: debug
  org.dromara.hmily: debug
  io.netty: info
  com.dhb.gts.javacourse.week8.hmilytcc: debug