server:
  port: 8084

#MYBATIS
mybatis.type-aliases-package: com.dhb.gts.javacourse.week5.entity
mybatis.configuration.map-underscore-to-camel-case: true
mybatis.configuration.use-generated-keys: true
mybatis.configuration.default-fetch-size: 100
mybatis.configuration.default-statement-timeout: 30
# mybatis typehandler
mybatis.type-handlers-package: com.dhb.gts.javacouse.week5.typehandler


#数据源配置 默认Hikari
#spring.datasource.url: jdbc:mysql://192.168.162.49:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username: gts
#spring.datasource.password: mysql
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# 数据源配置 durid
#spring.datasource.url: jdbc:mysql://192.168.162.49:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username: gts
#spring.datasource.password: mysql
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.type: com.alibaba.druid.pool.DruidDataSource

## C3P0
#spring.datasource.jdbcUrl: jdbc:mysql://192.168.162.49:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.user: gts
#spring.datasource.password: mysql
#spring.datasource.driverClass: com.mysql.cj.jdbc.Driver
#spring.datasource.type: com.mchange.v2.c3p0.ComboPooledDataSource


# DBCP
#spring.datasource.url: jdbc:mysql://192.168.162.49:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username: gts
#spring.datasource.password: mysql
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.type: org.apache.commons.dbcp2.BasicDataSource

spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.validationQuery: SELECT 1
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat

## 读写分离，多数据源配置
#spring.datasource.dynamic.primary: master
#spring.datasource.dynamic.strict: false
#spring.datasource.dynamic.master.type: com.zaxxer.hikari.HikariDataSource
#spring.datasource.dynamic.master.url: jdbc:mysql://192.168.161.114:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.dynamic.master.username: gts
#spring.datasource.dynamic.master.password: mysql
#spring.datasource.dynamic.master.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.dynamic.slave1.type: com.zaxxer.hikari.HikariDataSource
#spring.datasource.dynamic.slave1.url: jdbc:mysql://192.168.161.115:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.dynamic.slave1.username: gts
#spring.datasource.dynamic.slave1.password: mysql
#spring.datasource.dynamic.slave1.driver-class-name: com.mysql.cj.jdbc.Driver

# 自定义的动态数据源配置
custom:
  datasource:
    - key: master
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.161.114:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: gts
      password: mysql
      default: true
      initialSize: 20
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
    - key: slave1
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.161.115:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC&defaultStatementTimeout=60
      username: gts
      password: mysql
    - key: slave2
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.161.114:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC&defaultStatementTimeout=60
      username: gts
      password: mysql 

#线程池配置
async.executor.thread.core_pool_size: 20
# 最大线程数
async.executor.thread.max_pool_size: 20
# 任务队列大小
async.executor.thread.queue_capacity: 50
# 线程池中线程的名称前缀
async.executor.thread.name.prefix: async-service-
# 缓冲队列中线程的空闲时间
async.executor.thread.keep_alive_seconds: 100

#shardingSphereJDBC配置
spring.shardingsphere.datasource.names: master,slave1
spring.shardingsphere.datasource.common.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.common.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.common.maxWait: 60000
spring.shardingsphere.datasource.common.initialSize: 5
spring.shardingsphere.datasource.common.minIdle: 5
spring.shardingsphere.datasource.common.maxActive: 20
spring.shardingsphere.datasource.master.jdbc-url: jdbc:mysql://192.168.161.114:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.shardingsphere.datasource.master.username: gts
spring.shardingsphere.datasource.master.password: mysql
spring.shardingsphere.datasource.slave1.jdbc-url: jdbc:mysql://192.168.161.115:3306/gts?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.shardingsphere.datasource.slave1.username: gts
spring.shardingsphere.datasource.slave1.password: mysql

# 主数据源名称
spring.shardingsphere.rules.replica-query.data-sources.rw.primary-data-source-name: master
# 从数据源名称，多个从数据源用逗号分隔
spring.shardingsphere.rules.replica-query.data-sources.rw.replica-data-source-names: slave1
# 负载均衡算法名称
spring.shardingsphere.rules.replica-query.data-sources.rw.load-balancer-name: ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.round-robin.type: ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.round-robin.props.workId: 1
#是否启用查询一致性路由
spring.shardingsphere.rules.replica-query.data-sources.rw.query-consistent: true


# 打开sql输出日志
spring.shardingsphere.props.sql.show: true


logging.level.org.springframework: debug