spring.profiles.active: week8
      
server:
  port: 8084

#MYBATIS
mybatis.type-aliases-package: com.dhb.gts.javacourse.week5.entity
mybatis.configuration.map-underscore-to-camel-case: true
mybatis.configuration.use-generated-keys: true
mybatis.configuration.default-fetch-size: 100
mybatis.configuration.default-statement-timeout: 30
# mybatis typehandler
mybatis.type-handlers-package: com.dhb.gts.javacouse.week5.typehandler



logging.level.org.springframework: debug