#kafka ?? 
spring.kafka.bootstrap-servers: 192.168.162.201:9092,192.168.162.202:9092,192.168.162.203:9092

# prodice??
spring:
  kafka:
    producer:
      #????
      retries: 0 
      #????(??0 1 all/-1)???????????????????????????ack???
      acks: 1
      #????
      batch-size: 16384
    
      properties:
        #????
        linger:
          ms: 0
      # ??????
        partitioner:
          class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
      #??????
      buffer-memory: 33554432
      # Kafka????????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      
    # consumer??    
    consumer:
      properties:
        # ??????ID
        group:
          id: defaultConsumerGroup
        
      # ??????offset
      enable-auto-commit: true
      # ??offset??(??????????offset)
      auto-commit-interval: 1000
      # ?kafka?????offset?offset??????????offset:
      # earliest:?????????offset;
      # latest:?????????offset(???????????);
      # none:??????????????offset,?????;
      auto-offset-reset: latest
      # Kafka????????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ?????????
      max-poll-records: 50


    listener:
      # ??????topic????????????(??
      missing-topics-fatal: false
      # ??????
      type: batch
      
    