server:
  port: 8080
  
spring:
  activemq:
    broker-url: tcp://192.168.161.114:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 5
      idle-timeout: 30000
  jms:
    pub-sub-domain: false
